name: Sims Deployment CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Get tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Commit and push changes
        run: |
          # Fetch production branch or create if it doesn't exist
          git fetch origin production || git checkout -b production
          git checkout production
          
          # Temporarily store production versions of the files
          cp resources/views/components/pengurus-sidebar.blade.php pengurus-sidebar.temp
          cp resources/views/components/pemohon-sidebar.blade.php pemohon-sidebar.temp
          
          # Merge the tagged commit into production
          git merge ${{ steps.get_tag.outputs.TAG }} --strategy-option ours --no-ff -m "Merge tag ${{ steps.get_tag.outputs.TAG }} into production"
          
          # Restore the production versions
          cp pengurus-sidebar.temp resources/views/components/pengurus-sidebar.blade.php
          cp pemohon-sidebar.temp resources/views/components/pemohon-sidebar.blade.php
          
          # Clean up temp files
          rm pengurus-sidebar.temp pemohon-sidebar.temp
          
          # Update version in files
          sed -i "s/{{ 'v[0-9]\+\.[0-9]\+\.[0-9]\+'  }}/{{ steps.get_tag.outputs.TAG }}/" resources/views/components/pengurus-sidebar.blade.php
          sed -i "s/{{ 'v[0-9]\+\.[0-9]\+\.[0-9]\+'  }}/{{ steps.get_tag.outputs.TAG }}/" resources/views/components/pemohon-sidebar.blade.php
          
          # Force add the version updates (in case of no changes)
          git add -f resources/views/components/pengurus-sidebar.blade.php
          git add -f resources/views/components/pemohon-sidebar.blade.php
          git commit -m "Update APP_VERSION to ${{ steps.get_tag.outputs.TAG }}" || echo "No version changes to commit"
          
          # Push to production
          git push origin production
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/sims
            git fetch origin production
            git reset --hard origin/production
            
            # Configure git to avoid divergent branch issues
            git config pull.rebase false

            # Pull changes (should be clean now)
            git pull origin production